### ISSUE TITLE
how to handle if there is a library upgrade on build.gradle? 

### ISSUE THREAD

**Issue by sagrawal2418** [erikjhordan-rey/People-MVVM#29]
I am looking into the way how you broke down the build.gradle and created a dependencies.gradle file. How will we get lint error if we have a new library available to upgrade by doing this?

**Comment by erikjhordan-rey** [comment]
unfortunately, it's not possible when is created in this way I recommend don't use `dependencies.gradle` anymore, use just an extension for the number version.
