### ISSUE TITLE
Data not showing

### ISSUE THREAD

**Issue by vishalvasani18** [erikjhordan-rey/People-MVVM#33]
I try to open your project and build successful but data not showing.

Error showing like =" There seems to have been some error."

pls, fix this issue.

**Comment by erikjhordan-rey** [comment]
<img width="404" alt="imagen" src="https://user-images.githubusercontent.com/5893477/87576985-cd015780-c697-11ea-9104-5f9b31f0d785.png">

it works! I can't see any issue
